
package View;
import Entity.EntityPegawai;
import Entity.EntityPembelian;
import Entity.EntityProduk;
import Interface.InterfacePegawai;
import Interface.InterfacePembelian;
import Interface.InterfaceProduk;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Until.Auth;

public class FrmPembelian extends javax.swing.JInternalFrame {
    private DefaultTableModel dtmPembelian, dtmkodePegawai, dtmKodeProduk;
    private String[] tabelHeader, tabelHeaderPegawai, tabelHeaderProduk;
    private List<EntityPegawai> listPegawai;
    private List<EntityProduk> listProduk;
    
    private InterfacePembelian pembelianDAO;
    private InterfacePegawai pegawaiDAO;
    private InterfaceProduk produkDAO;
    
    private EntityPembelian p;
    private int total_beli = 0;
    
    private String tanggal(){
       DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
       Date d = new Date();
       return df.format(d);    
   }
   
   private String kodeDepan(){
       DateFormat df = new SimpleDateFormat("ddMM");
       Date d = new Date();
       return df.format(d);
   }
    
   private void aturButton(boolean status){
       btnAdd.setEnabled(status);
       btnSave.setEnabled(!status);
       if(status==true){
           btnExit.setText("Exit");
       }else{
           btnExit.setText("Cancel");
       }
   }
    
   private void aturTeks(){
       txtKodePembelian.setEditable(false);
       txtKodeProduk.setEditable(false);
       txtKodepegawai.setEditable(false);
       txtTanggal.setEditable(false);
       txtQty.setEditable(false);
       txtHargaSatuan.setEditable(false);
       txtTotal.setEditable(false);
       txtTotalbeli.setEditable(false);
   }
   
   private void teksKosong(){
       txtKodePembelian.setText("");
       txtKodeProduk.setText("");
       txtKodepegawai.setText("");
       txtTanggal.setText("");
       txtQty.setText("");
       txtHargaSatuan.setText("");
       txtTotal.setText("");
       txtTotalbeli.setText("");
   }
  
    private void aturTabel(){
        tabelHeader = new String[]{"KODE PRODUK", "NAMA PRODUK", "HARGA", "QTY", "JUMLAH"};
        dtmPembelian = new DefaultTableModel(null, tabelHeader);
        tabelPembelian.setModel(dtmPembelian);
    }
    
   private void refreshIsitabelPegawai(){
        listPegawai = pegawaiDAO.selectPegawai(txtCariPegawai.getText(), txtCariPegawai.getText());
        dtmkodePegawai = (DefaultTableModel) tabelCariPegawai.getModel();
        dtmkodePegawai.setRowCount(0);
        for(EntityPegawai data : listPegawai){
            dtmkodePegawai.addRow(new Object[]{data.getKode_pegawai(),data.getNama()});
        }
    }
   private void refreshIsitabelProduk(){
       listProduk = produkDAO.selectProduk(txtCarikodeProduk.getText(), txtCarikodeProduk.getText());
       dtmKodeProduk = (DefaultTableModel) tabelcarikodeProduk.getModel();
       dtmKodeProduk.setRowCount(0);
       for(EntityProduk data : listProduk){
           dtmKodeProduk.addRow(new Object[]{data.getKode_produk(),data.getNama_produk(),data.getHarga_beli_satuan()});
       }
   }

    public FrmPembelian() {
        initComponents();
        pembelianDAO = Factory.Factory.getPembelianDAO();
        aturTabel();
        aturButton(true);
        btnAdd.requestFocus();
        aturTeks();
        
        pegawaiDAO = Factory.Factory.getPegawaiDAO();
        tabelHeaderPegawai = new String[]{"KODE PEGAWAI", "NAMA"};
        dtmkodePegawai = new DefaultTableModel(null, tabelHeaderPegawai);
        tabelCariPegawai.setModel(dtmkodePegawai);
        refreshIsitabelPegawai();
        
        produkDAO = Factory.Factory.getProdukDAO();
        tabelHeaderProduk = new String[]{"KODE", "NAMA", "HARGA SATUAN"};
        dtmKodeProduk = new DefaultTableModel(null, tabelHeaderProduk);
        tabelcarikodeProduk.setModel(dtmKodeProduk);
        refreshIsitabelProduk();
        
        txtKodepegawai.setText(Auth.getKode_pegawai());
        txtKodepegawai.setEditable(false);
        btnCariproduk.setEnabled(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogCariPegawai = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelCariPegawai = new javax.swing.JTable();
        txtCariPegawai = new javax.swing.JTextField();
        dialogCariKodeProduk = new javax.swing.JDialog();
        txtCarikodeProduk = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelcarikodeProduk = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtKodePembelian = new javax.swing.JTextField();
        txtKodepegawai = new javax.swing.JTextField();
        txtTanggal = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPembelian = new javax.swing.JTable();
        btnExit = new javax.swing.JButton();
        txtTotalbeli = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtKodeProduk = new javax.swing.JTextField();
        txtNamaProduk = new javax.swing.JTextField();
        txtQty = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnCariproduk = new javax.swing.JButton();
        txtTotal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        txtHargaSatuan = new javax.swing.JTextField();
        btnRemove = new javax.swing.JButton();
        btnInsert = new javax.swing.JButton();

        dialogCariPegawai.setMinimumSize(new java.awt.Dimension(400, 243));

        tabelCariPegawai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelCariPegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelCariPegawaiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelCariPegawai);

        javax.swing.GroupLayout dialogCariPegawaiLayout = new javax.swing.GroupLayout(dialogCariPegawai.getContentPane());
        dialogCariPegawai.getContentPane().setLayout(dialogCariPegawaiLayout);
        dialogCariPegawaiLayout.setHorizontalGroup(
            dialogCariPegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogCariPegawaiLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(dialogCariPegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                    .addComponent(txtCariPegawai))
                .addContainerGap())
        );
        dialogCariPegawaiLayout.setVerticalGroup(
            dialogCariPegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogCariPegawaiLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(txtCariPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        dialogCariKodeProduk.setMinimumSize(new java.awt.Dimension(400, 341));

        tabelcarikodeProduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelcarikodeProduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelcarikodeProdukMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelcarikodeProduk);

        javax.swing.GroupLayout dialogCariKodeProdukLayout = new javax.swing.GroupLayout(dialogCariKodeProduk.getContentPane());
        dialogCariKodeProduk.getContentPane().setLayout(dialogCariKodeProdukLayout);
        dialogCariKodeProdukLayout.setHorizontalGroup(
            dialogCariKodeProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogCariKodeProdukLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(dialogCariKodeProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCarikodeProduk)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE))
                .addContainerGap())
        );
        dialogCariKodeProdukLayout.setVerticalGroup(
            dialogCariKodeProdukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogCariKodeProdukLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(txtCarikodeProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(242, 48, 67));
        jPanel1.setPreferredSize(new java.awt.Dimension(245, 55));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DATA PEMBELIAN");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ico_walls.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(507, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel1))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data Pembelian", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(242, 48, 67))); // NOI18N

        jLabel2.setText("Kode Pembelian");

        jLabel3.setText("Kode Pegawai");

        jLabel4.setText("Tanggal");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtKodePembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKodepegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtKodePembelian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtKodepegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        tabelPembelian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelPembelian);

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        jLabel18.setText("Rp.");

        jLabel13.setText("Total");

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Save_16x16.png"))); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 749, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addGap(2, 2, 2)
                .addComponent(txtTotalbeli, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnExit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(txtTotalbeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18))
                    .addComponent(btnAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit)
                .addGap(69, 69, 69))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Es yang Dibeli", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(242, 48, 67))); // NOI18N

        jLabel5.setText("Kode Produk");

        jLabel6.setText("Nama Produk");

        jLabel7.setText("Qty");

        txtQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtyActionPerformed(evt);
            }
        });
        txtQty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQtyKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQtyKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQtyKeyTyped(evt);
            }
        });

        jLabel9.setText("Total");

        btnCariproduk.setText("jButton1");
        btnCariproduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariprodukActionPerformed(evt);
            }
        });

        jLabel11.setText("Pcs");

        jLabel8.setText("Harga Satuan");

        btnRemove.setBackground(javax.swing.UIManager.getDefaults().getColor("CheckBoxMenuItem.selectionBackground"));
        btnRemove.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnRemove.setText("ʌ");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnInsert.setBackground(javax.swing.UIManager.getDefaults().getColor("CheckBoxMenuItem.selectionBackground"));
        btnInsert.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnInsert.setText("v");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txtKodeProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCariproduk, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11))
                            .addComponent(txtNamaProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btnInsert)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRemove))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtHargaSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtKodeProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(btnCariproduk)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtNamaProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRemove)
                            .addComponent(btnInsert))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtHargaSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 769, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtyActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        txtKodePembelian.setText(pembelianDAO.kodeBaru(tanggal(), kodeDepan()));
        txtTanggal.setText(tanggal());
        btnCariproduk.setEnabled(true);
        txtQty.setEditable(true);
        aturButton(false);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        p = new EntityPembelian();
        p.setKode_pembelian(txtKodePembelian.getText());
        p.setKode_pegawai(txtKodepegawai.getText());
        p.setTanggal(txtTanggal.getText());
        pembelianDAO.insertPembelian(p);
        
        //insert detail pembelian
        int baris = tabelPembelian.getRowCount();
        for(int i=0;i<baris;i++){
            p.setKode_produk(dtmPembelian.getValueAt(i, 0).toString());
            p.setQty(Integer.parseInt(dtmPembelian.getValueAt(i, 3).toString()));
            p.setHarga_satuan(Integer.parseInt(dtmPembelian.getValueAt(i, 2).toString()));
            p.setTotal(Integer.parseInt(dtmPembelian.getValueAt(i, 4).toString()));
            pembelianDAO.insertDetailPembelian(p);
       
        }
        aturButton(true);
        teksKosong();
        aturTabel();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        if(btnExit.getText().equals("Exit")){
            FrmTampilPembelian p = new FrmTampilPembelian();
            JDesktopPane dp = getDesktopPane();
            dp.add(p);
            p.setVisible(true);
            this.dispose();

        }else{
            aturButton(true);
            teksKosong();
            txtKodeProduk.setText("");
            txtNamaProduk.setText("");
            txtHargaSatuan.setText("");
            txtQty.setText("");
            txtTotal.setText("");
            aturTabel();
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void tabelCariPegawaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelCariPegawaiMouseClicked
        int baristabelcaripegawai = tabelCariPegawai.getSelectedRow();
        txtKodepegawai.setText(tabelCariPegawai.getValueAt(baristabelcaripegawai, 0).toString());
        dialogCariPegawai.setVisible(false);
    }//GEN-LAST:event_tabelCariPegawaiMouseClicked

    private void tabelcarikodeProdukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelcarikodeProdukMouseClicked
        int baristabelcariProduk = tabelcarikodeProduk.getSelectedRow();
        txtKodeProduk.setText(tabelcarikodeProduk.getValueAt(baristabelcariProduk, 0).toString());
        txtNamaProduk.setText(tabelcarikodeProduk.getValueAt(baristabelcariProduk, 1).toString());
        txtHargaSatuan.setText(tabelcarikodeProduk.getValueAt(baristabelcariProduk, 2).toString());
        dialogCariKodeProduk.setVisible(false);
    }//GEN-LAST:event_tabelcarikodeProdukMouseClicked

    private void btnCariprodukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariprodukActionPerformed
        dialogCariKodeProduk.setVisible(true);
    }//GEN-LAST:event_btnCariprodukActionPerformed

    private void txtQtyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtyKeyPressed
        if(txtQty.getText().equalsIgnoreCase("")){
            txtTotal.setText("");
        }else{
            int harga = Integer.parseInt(txtHargaSatuan.getText());
            int qty = Integer.parseInt(txtQty.getText());
            int total = harga*qty;
            txtTotal.setText(String.valueOf(total));
        }
        
        if(evt.getKeyCode()==evt.VK_ENTER){
            int harga = Integer.parseInt(txtHargaSatuan.getText());
            int qty = Integer.parseInt(txtQty.getText());
            int total = harga*qty;
            txtTotal.setText(String.valueOf(total));
        }
    }//GEN-LAST:event_txtQtyKeyPressed

    private void txtQtyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtyKeyReleased
        if(txtQty.getText().equalsIgnoreCase("")){
            txtTotal.setText("");
        }else{
            int harga = Integer.parseInt(txtHargaSatuan.getText());
            int qty = Integer.parseInt(txtQty.getText());
            int total = harga*qty;
            txtTotal.setText(String.valueOf(total));
        }
    }//GEN-LAST:event_txtQtyKeyReleased

    private void txtQtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtyKeyTyped
        if(txtQty.getText().equalsIgnoreCase("")){
            txtTotal.setText("");
        }else{
            int harga = Integer.parseInt(txtHargaSatuan.getText());
            int qty = Integer.parseInt(txtQty.getText());
            int total = harga*qty;
            txtTotal.setText(String.valueOf(total));
        }
    }//GEN-LAST:event_txtQtyKeyTyped

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        if(tabelPembelian.getSelectedRow() >= 0){
            dtmPembelian.removeRow(tabelPembelian.getSelectedRow());
            
            int baris = tabelPembelian.getRowCount();
            total_beli = 0;
            for (int i = 0; i < baris; i++) {
                total_beli = total_beli + Integer.parseInt(dtmPembelian.getValueAt(i, 4).toString());
            }
            txtTotalbeli.setText(String.valueOf(total_beli));
        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        if(txtTotal.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Kok Total nya Kosong ya?");
            txtQty.requestFocus();
        }else{
        dtmPembelian.addRow(new Object[]{txtKodeProduk.getText(),txtNamaProduk.getText(),txtHargaSatuan.getText(),txtQty.getText(),txtTotal.getText()});
        txtKodeProduk.setText("");
        txtNamaProduk.setText("");
        txtHargaSatuan.setText("");
        txtQty.setText("");
        txtTotal.setText("");
        
        int baris = tabelPembelian.getRowCount();
        total_beli = 0;
        for(int i=0;i<baris;i++){
            total_beli = total_beli + Integer.parseInt(dtmPembelian.getValueAt(i, 4).toString());
        }
        txtTotalbeli.setText(String.valueOf(total_beli));
        }
    }//GEN-LAST:event_btnInsertActionPerformed
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCariproduk;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSave;
    private javax.swing.JDialog dialogCariKodeProduk;
    private javax.swing.JDialog dialogCariPegawai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tabelCariPegawai;
    private javax.swing.JTable tabelPembelian;
    private javax.swing.JTable tabelcarikodeProduk;
    private javax.swing.JTextField txtCariPegawai;
    private javax.swing.JTextField txtCarikodeProduk;
    private javax.swing.JTextField txtHargaSatuan;
    private javax.swing.JTextField txtKodePembelian;
    private javax.swing.JTextField txtKodeProduk;
    private javax.swing.JTextField txtKodepegawai;
    private javax.swing.JTextField txtNamaProduk;
    private javax.swing.JTextField txtQty;
    private javax.swing.JTextField txtTanggal;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTotalbeli;
    // End of variables declaration//GEN-END:variables
}
